### ISSUE TITLE
Troubleshoot slow DMV process

### ISSUE THREAD

**Issue by jkarpen** [cagov/data-infrastructure#364]
Per Andrew, the DMV queries are taking longer to run as the data volume increases. He asked for us to help Erin look for ways to improve the performance.

**Comment by tnrahim** [comment]
After assessing the DMV queries we came up with the following modifications to improve query performance.

1. Change the table to incremental
2. Use variables instead of subqueries for case statements.

Currently DMV takes about 2 hours to execute. We will reevaluate once the modifications are complete.

**Comment by tnrahim** [comment]
Key Changes and Impacts
No Changes - Initial Runtime of query was approximately 2 hours.
Updated Case Statement so that it did not use subqueries.
Updated table to be clustered by snowflake load date
DMV Query took 1.5 hours
Updated to Incremental Merge
DMV Query took 1.25 hours
Changed Incremental strategy to delete+insert 
DMV Query took 40 mins
Resolved data issue that caused duplicate rows to be inserted into DMV Query.
Full-Refresh DMV Query 25 mins
Incremental Load 6 mins
