### ISSUE TITLE
Assign `LOGGER` role to `TRANSFORMER` role

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#428]
In order to access cost information as part of our normal data pipelines (cf. #427), the `TRANSFORMER` role probably needs access to the `LOGGER` role.

I'm a little agnostic as to whether this is useful to do in terraform. If it is, it could probably be at the top-level, rather than in the "elt" module.

**Comment by ram-kishore-odi** [comment]
I would also think a little more about this and come back with additional feedback.

**Comment by ian-r-rose** [comment]
Yeah, it may also be that a different permission structure is helpful here

**Comment by ram-kishore-odi** [comment]
Hi @ian-r-rose, please see my feedback below. I initially tried assigning the LOGGER role to the TRANSFORMER at the top-level rather than in the "elt" module. With the current setup, I was not successful because all the functional roles are defined in the elt module. Consequently, I raised a PR with the code inside the elt module. If you think this option is acceptable or desirable, please let me know.

**Option 1:** If this assignment is applicable only to the default ODI infrastructure setup and not for other agencies, we may need to handle it outside of Terraform as a workaround. Later, we could refactor the code to define it outside of the elt module.

**Option 2:** The other option, in my view, would be to make this repository purely generic to be used across all agencies. We can then set up separate customizations for ODI by referencing this elt module, similar to how we do in Caltrans (e.g., github.com/cagov/data-infrastructure.git//terraform/snowflake/modules/elt?ref=ebd59ff). This approach would keep the main repository clean and maintain ODI-specific customizations in one place, avoiding the inclusion of unnecessary permissions for other agencies.

**Comment by ian-r-rose** [comment]
You're absolutely correct that it is easier to add the grant in the "elt" module. That said, I'm not sure we want to do that in general for security reasons. Basically, I don't think the "developer" role should have access to `SNOWFLAKE` by default, it's more of a special case for our orgadmin-reasons.

I'm not sure I understand your proposal in **Option 2**, can you elaborate a bit more?

I do think I see a couple of other options for the grant:

1. We do it at the top level, but we don't refer to the logger and transformer roles via their resource references. Instead, we construct them via string interpolation, e.g. `LOGGER_{environment}` and `TRANSFORMER_{environment}`. This would be a hack, as it is less robust than referring to the resource names, but might be an okay thing to do as a special case
2. The *correct* way to refer to resources in modules is to export those resource names as module outputs. We could export the functional roles as outputs from the "elt" module, which could then be picked up at the top level. There are actually a lot of places where we could use outputs rather than manual string construction to make the modules more robust (it's been a backlog item in my head for a bit)

**Comment by ram-kishore-odi** [comment]
I agree that the "developer" role should not have access to Snowflake. The point is very valid.

Option 1 from your feedback is a creative hack that I hadn't considered 👍. It will certainly work for now.

Referring to resources in modules by exporting the resource names as module outputs is indeed a best practice, though it will require some code refactoring.

Regarding option 2 in my comments, I was referring to creating a new repo for ODI, referencing the ELT module from the existing data-infrastructure (main repo) repository, and maintaining ODI-specific customizations in the new repo, similar to what was done in the CARB and CalTrans projects. Keeping the main repo clean will avoid the inclusion of unnecessary permissions for other agencies. Please let me know if you have additional questions.

To unblock Taheer, I can manually add the grant. Once the code is ready, I can remove it from the state and proceed to apply the changes through Terraform. Please let me know if you are okay with this approach.

**Comment by ian-r-rose** [comment]
Yep, your plan sounds good!

**Comment by ian-r-rose** [comment]
Fixed by #445
